#! /usr/bin/env python3
from sokoban import sokoban_play
'''
field = create_sokoban_field()
field = sokoban_add(field, create_object('#', 0, 0))
field = sokoban_add(field, create_object('#', 0, 1))
field = sokoban_add(field, create_object('#', 0, 2))
field = sokoban_add(field, create_object('#', 0, 3))
field = sokoban_add(field, create_object('#', 0, 4))
field = sokoban_add(field, create_object('#', 0, 5))
field = sokoban_add(field, create_object('#', 0, 6))
field = sokoban_add(field, create_object('#', 1, 0))
field = sokoban_add(field, create_object('#', 1, 6))
field = sokoban_add(field, create_object('#', 2, 0))
field = sokoban_add(field, create_object('#', 2, 6))
field = sokoban_add(field, create_object('#', 3, 0))
field = sokoban_add(field, create_object('#', 3, 6))
field = sokoban_add(field, create_object('#', 4, 0))
field = sokoban_add(field, create_object('#', 4, 6))
field = sokoban_add(field, create_object('#', 5, 0))
field = sokoban_add(field, create_object('#', 5, 6))
field = sokoban_add(field, create_object('#', 6, 2))
field = sokoban_add(field, create_object('#', 6, 3))
field = sokoban_add(field, create_object('#', 6, 4))
field = sokoban_add(field, create_object('#', 5, 5))
field = sokoban_add(field, create_object('#', 6, 5))
field = sokoban_add(field, create_object('#', 6, 0))
#field = sokoban_add(field, create_object('#', 5, 5)
#field = sokoban_add(field, create_object('#', 5, 5))

field = sokoban_add(field, create_object('@', 3, 5))
field = sokoban_add(field, create_object('O', 3, 4))
field = sokoban_add(field, create_object('.', 3, 3))
field = sokoban_add(field, create_object('.', 3, 2))
field = sokoban_add(field, create_object('.', 3, 1))
'''
sokoban_play()
